apiVersion: v1
kind: Namespace
metadata:
  name: iot-observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-api-config
  namespace: iot-observability
data:
  HTTP_ADDRESS: ":8080"
  WORKERS: "8"
  QUEUE_CAPACITY: "4096"
  HISTORY_LIMIT: "1000"
  OFFLINE_AFTER: "5m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
  namespace: iot-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-api
  template:
    metadata:
      labels:
        app: iot-api
    spec:
      containers:
        - name: api
          image: ghcr.io/akash-anumolu/go-iot-observability-platform:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: iot-api-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: iot-api
  namespace: iot-observability
spec:
  selector:
    app: iot-api
  ports:
    - name: http
      port: 80
      targetPort: http
